### ISSUE TITLE
MAINTAINER deprecated

### ISSUE THREAD

**Issue by wkusnierczyk** [replicatedhq/dockerfilelint#71] opened 2017-04-13 18:24 UTC
The `MAINTAINER` instruction is deprecated:

* https://docs.docker.com/engine/reference/builder/#/maintainer-deprecated

Consider implementing a warning with suggestion to replace with `LABEL maintainer`.

**Comment by jadametz** [comment] 2017-06-29 20:24
Looks like this was solved in #69

**Comment by thomasbiddle** [comment] 2017-08-07 16:32
@jadametz 

Confirmed - just ran whatever the latest is:
```
Line 4: MAINTAINER "some@email.com"
Issue  Category      Title                 Description
    1  Deprecation   Deprecated as of      This INSTRUCTION is deprecated as of Docker 1.13
                     Docker 1.13
```

This can be closed.

**Comment by nexdrew** [comment] 2017-09-01 16:14
Thanks everyone! Not sure why this was left open, closing now.

**Closed by nexdrew** 2017-09-01 16:14 UTC

**Comment by dserodio** [comment] 2019-03-12 13:21
I added a MAINTAINER line to the www.fromlatest.io example and it didn't complain
